# Generated by Django 3.1.5 on 2021-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('faixa_etaria', models.IntegerField()),
                ('sinapse', models.CharField(max_length=1000)),
                ('ano', models.IntegerField()),
                ('duracao_minutos', models.IntegerField()),
                ('qualidade', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
