# Generated by Django 3.1.5 on 2021-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFilmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duracao_minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filme',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
