# Generated by Django 3.1.5 on 2021-03-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFilmes', '0002_auto_20210306_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='faixa_etaria',
            new_name='classind',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='duracao_minutos',
            new_name='tempo',
        ),
    ]
